### PR TITLE
feat/auto-play-slideBlock

### PR DESCRIPTION
**Pull request by MKMonkeyCat**
# Description

feat/auto-play-slideBlock

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by banahaker** [comment]
that's great
@SiongSng can it be merged?

**Comment by banahaker** [comment]
wait for me to check conflicts

**Comment by banahaker** [comment]
WHAT

**Review by SiongSng — APPROVED** [review]
LGTM!

**Comment by banahaker** [comment]
i just going to merge...

**Pull request merged**
