### PR TITLE
fix: RWD

### LINKED ISSUE #14: RWD bug
- When the mobile scale, it would a little problem appear.
 - The menu cause a display problem on mobile browser.

### PR DESCRIPTION
**Pull request by banahaker**
# [ Fix ] Display bug

- 解決了旋轉跑版的問題
- 解決menu會有超出範圍的問題

Fixes #14 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by banahaker** [comment]
@SiongSng What are you think about that problem I fix.

**Review by SiongSng — CHANGES_REQUESTED** [review]
<details><summary>Comment has been resolved by 菘菘</summary>

The menu position is still incorrect.
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /#/
Browser:   Firefox 99.0 on Linux x86_64
Viewport:  1920 x 891 @1x
Language:  zh-TW
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-15--lipoic-frontend.netlify.app%2F%23%2F&os=OS%20X&os_version=Big%20Sur&browser=Firefox&browser_version=99.0&resolution=1920x891&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-15--lipoic-frontend.netlify.app/#/) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=6273e651f02e4d0008bc1fff&commentID=6273e81b6a541a695ff856a6&resolution=unresolved)

</details>

**Comment by banahaker** [comment]
I solve this problem!!!!!
@SiongSng 
**And it's time to bad**

**Comment by banahaker** [comment]
Oh Fuxk!!!!!!!!!!!!!!!
I delete a style by accident, Waiting for me to fix it.

**Comment by banahaker** [comment]
I'd finished that, I'm going to bed

**Review by SiongSng — APPROVED** [review]
LGTM

**Pull request merged**
